<?php

/**
 * @file
 * Redirect first-time visitors to another site.
 */

/**
 * Implements hook_menu().
 */
function initial_redirect_menu() {
  $items['admin/config/user-interface/initial-redirect'] = array(
    'title' => 'Initial Redirect',
    'description' => 'Configure redirects for first time visitors.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('initial_redirect_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'initial_redirect.admin.inc',
  );
  return $items;
}

/**
 * Implements template_preprocess_html().
 */
function initial_redirect_html_head_alter(&$head_elements) {
  if (variable_get('initial_redirect_active', FALSE) && variable_get('initial_redirect_url', FALSE)) {
    // Reference external libraries required by jStorage.
    drupal_add_library('system', 'jquery.cookie');
    // Add settings for JS.
    $settings = array(
      'initialRedirect' => array(
        'url' => variable_get('initial_redirect_url', FALSE),
        'ts' => variable_get('initial_redirect_ts', 0),
      ),
    );
    drupal_add_js($settings, 'setting');
  }
}